### ISSUE TITLE
200 million fibonacci number in 1 second (20x faster than Binet formula) using Combinatoric / Dynamic Programming

### ISSUE THREAD

**Issue by lehuyduc** [SheafificationOfG/Fibsonisheaf#1]
https://github.com/lehuyduc/fast-fibonacci
Just clone and run `./full_run.sh` to calculate F(10^7). To calculate F(10^8) or F(n) in general, use it like `./run.sh 100000000`

Some benchmark result (time to calculate N-th fibonacci number, unit: ms). Ubuntu 18.04, g++ 12.2.0, Ryzen 5900X
``````````````
N      | Binet   | DP    | Fibsonicci field_ext
10^6 | 55.24  | 4.55  | 149
10^7 | 968.1  | 29.1  | 2798
10^8 | 16271 | 460   | 124995
2*10^8  | 35569 | 950 | longer
``````````````
Let's solve the following: starting at point `0` on x-axis, count number of paths to reach point `n` if at each point `x` we can jump to `x + 1` or `x + 2`.

F(0) = 1, because obvious
F(1) = 1, because there's only 1 way to move from 0 -> 1
To reach `n`, there's 2 option:
- Moving to `n - 1`, then jump 1 step to n
- Moving to `n - 2`, then jump 2 steps to n
=> F(n) = F(n - 1) + F(n - 2)
=> F(n) = Fibonacci(n  + 1)

We solve for odd and even `n` separate.
**1. F(2 * k)**
We can split it into 2 more mutually exclusive cases:
a) Paths `0->2k`, that includes `k`:
- First we go `0->k`, which has `F(k)` paths.
- Then we need to move `k->2 * k`, which is exactly the same as moving from `0->k`.
=> Number of path = F(k) * F(k)

b) Paths `0->2k`, without including `k`:
- We go `0->k-1` -> F(k - 1) options
- We jump 2 steps to `k+1` -> 1 option
- We jump from `k + 1 -> 2k` => F(2k - (k + 1)) = F(k - 1)
=> Number of path = F(k - 1) * 1 * F(k -1)

**=> F(2 * k) = F(k) * F(k) + F(k - 1) * F(k - 1)**

**2. F(2 * k + 1)**
We can split it into 2 same mutually exclusive cases:
a) Moving from `0->k`, then `k -> 2 * k + 1` => F(k) * F(k + 1)
b) Moving from `0->k - 1`, `k-1 -> k + 1`, `k + 1 -> 2k + 1` => F(k - 1) * 1 * F(k)

**=> F(2 * k + 1) = F(k) * F(k + 1) + F(k - 1) * F(k)**

**FINAL FORMULA:**
```
F(2 * k) = F(k) * F(k) + F(k - 1) * F(k - 1)
F(2 * k + 1) = F(k) * F(k + 1) + F(k - 1) * F(k)
```

**Comment by GSheaf** [comment]
Nice solution!
However, this project doesn't have any plans for collaboration (yet?), and using GMP is not within the intended scope (except as a comparison).

**Comment by lehuyduc** [comment]
No problem. I shared this because you like math solutions and this one is not in the video :D 

The method doesn't require GMP. You can replace GMP with any other library or your own bignum class.
